# Logistic regression - A nonlinear optimization perspective

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import time
from sklearn.linear_model import LogisticRegression as LogisticSklearn
from sklearn import datasets
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.model_selection import train_test_split

Notice sklearn is used as benchmark model

## Custom operators

In [2]:
from logistic import LogisticRegression
from optimizers import QuasiNewton, ConjugateGradient, Newton, SteepestDescent

## Iris dataset

In [3]:
# import some data to play with
iris = datasets.load_iris()
X = iris.data[:, :]
y = iris.target

In [4]:
start = time.time()

# Create an instance of Logistic Regression Classifier and fit the data.
logistic_sklearn = LogisticSklearn(penalty='none', solver='lbfgs')
logistic_sklearn.fit(X, y)

end = time.time()
duration = end - start

print(confusion_matrix(y, logistic_sklearn.predict(X)))
print(f"Accuracy: {accuracy_score(y, logistic_sklearn.predict(X)):.3f}")

print(f"Duration of {duration:.4f} seconds")

[[50  0  0]
 [ 0 49  1]
 [ 0  1 49]]
Accuracy: 0.987
Duration of 0.0199 seconds


In [5]:
start = time.time()

logistic = LogisticRegression(optimizer=ConjugateGradient, f_tol=1e-6, max_iter=500, preprocess=True)
logistic.fit(X, y)

end = time.time()
duration = end - start

print(confusion_matrix(y, logistic.predict(X)))
print(f"Accuracy: {accuracy_score(y, logistic.predict(X)):.3f}")

n_iter = logistic.opt.result["iter"]
print(f"Iter: {n_iter}")

print(f"Duration of {duration:.4f} seconds")

[[50  0  0]
 [ 0 49  1]
 [ 0  1 49]]
Accuracy: 0.987
Iter: 317
Duration of 0.5046 seconds


In [6]:
start = time.time()

logistic = LogisticRegression(optimizer=QuasiNewton, f_tol=1e-6, max_iter=500, preprocess=True)
logistic.fit(X, y)

end = time.time()
duration = end - start

print(confusion_matrix(y, logistic.predict(X)))
print(f"Accuracy: {accuracy_score(y, logistic.predict(X)):.3f}")

n_iter = logistic.opt.result["iter"]
print(f"Iter: {n_iter}")

print(f"Duration of {duration:.4f} seconds")

[[50  0  0]
 [ 0 49  1]
 [ 0  1 49]]
Accuracy: 0.987
Iter: 70
Duration of 0.0486 seconds


sklearn is faster for sure, but our quasi-newton optimizer is not bad...

In [7]:
start = time.time()

logistic = LogisticRegression(optimizer=SteepestDescent, f_tol=1e-6, max_iter=500, preprocess=True)
logistic.fit(X, y)

end = time.time()
duration = end - start

print(confusion_matrix(y, logistic.predict(X)))
print(f"Accuracy: {accuracy_score(y, logistic.predict(X)):.3f}")

n_iter = logistic.opt.result["iter"]
print(f"Iter: {n_iter}")

print(f"Duration of {duration:.4f} seconds")

[[50  0  0]
 [ 0 48  2]
 [ 0  1 49]]
Accuracy: 0.980
Iter: 501
Duration of 0.5713 seconds


And steepest descent never got there...

## Breast cancer dataset

In [8]:
breast = datasets.load_breast_cancer()

X = breast.data
y = breast.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=12)

norm_factor = X_train.std(axis=0)

X_train = X_train / norm_factor
X_test = X_test / norm_factor

In [9]:
# Create an instance of Logistic Regression Classifier and fit the data.
logistic_sklearn = LogisticSklearn(penalty='l2', solver='lbfgs', max_iter=1000, tol=1e-6)
logistic_sklearn.fit(X_train, y_train)

y_train_p = logistic_sklearn.predict(X_train)
y_pred = logistic_sklearn.predict(X_test)

print(confusion_matrix(y_train, y_train_p))
print(confusion_matrix(y_test, y_pred))
print(f"Accuracy: {accuracy_score(y_test, y_pred):.3f}")

[[161   3]
 [  2 289]]
[[45  3]
 [ 0 66]]
Accuracy: 0.974


In [10]:
logistic = LogisticRegression(f_tol=1e-6, l2=1e-4, max_iter=1000, preprocess=True, optimizer=QuasiNewton)
logistic.fit(X_train, y_train)

y_train_p = logistic.predict(X_train)
y_pred = logistic.predict(X_test)

print(confusion_matrix(y_train, y_train_p))
print(confusion_matrix(y_test, y_pred))
print(f"Accuracy: {accuracy_score(y_test, y_pred):.3f}")

[[160   4]
 [  1 290]]
[[45  3]
 [ 0 66]]
Accuracy: 0.974


Ground truth: Lines\
Prediction: Columns